name: Deploy frontend on ec2
on:
  push:
    branches:
      - main
jobs:
  Deploy:
    runs-on: ubantu-latest
  steps:
    name:Checkout Code
    uses:action/checkout@v3

    name:deploy to ec2 via ssh
    uses:appleboy/ssh-acton@master

  with:
    host:${{secrets.EC2_HOST}}
    username:ec2-user
    key:${{secretes.DEPLOY_KEY}}

  scripts: |
      cd app/frontend/ecomerce
      git pull origin main
      npm install
      npm run build
      sudo cp -r dist/*  /home/ec2-user/frontend-app/live
